package tiendavirtual.interfaz;

public class Mensajes_enviados_administrador {
	public Vista_centro_de_mensajes_administrador _vista_centro_de_mensajes_administrador;
	public Lista_mensajes_enviados_administrador _lista_mensajes_enviados_administrador;
}